using BenchmarkDotNet.Reports;
using BenchmarkDotNet.Running;
using XLBench;
using XLBench.Config;

// Run all (or CLI-filtered) benchmarks with the shared comparison config, then publish
// the generated GitHub-flavored markdown into ./docs for GitHub Pages.
//
// Examples:
//   dotnet run -c Release                       run everything
//   dotnet run -c Release -- --filter *Read*     only read benchmarks
//   dotnet run -c Release -- --job short         faster, lower-fidelity run
var config = BenchmarkConfig.Create();

var summaries = BenchmarkSwitcher
    .FromAssembly(typeof(Program).Assembly)
    .Run(args, config);

ResultsPublisher.Publish(summaries);

namespace XLBench
{
    /// <summary>Marker type used to locate the benchmark assembly.</summary>
    internal sealed class Program;

    /// <summary>
    /// Copies BenchmarkDotNet's generated GitHub markdown reports into the docs/ folder
    /// (published via GitHub Pages), prefixed with a run-metadata header. The docs
    /// directory is resolved from <c>XLBENCH_DOCS</c> if set, otherwise ./docs relative
    /// to the current working directory (the repo root when run via scripts/run-benchmarks.ps1).
    /// </summary>
    internal static class ResultsPublisher
    {
        public static void Publish(IEnumerable<Summary> summaries)
        {
            var summaryList = summaries.ToList();
            if (summaryList.Count == 0)
            {
                Console.WriteLine("[XLBench] No summaries produced; nothing to publish.");
                return;
            }

            var docsDir = Environment.GetEnvironmentVariable("XLBENCH_DOCS")
                          ?? Path.Combine(Directory.GetCurrentDirectory(), "docs");
            Directory.CreateDirectory(docsDir);

            // BenchmarkDotNet writes *-report-github.md under the artifacts results folder.
            var artifactsResults = summaryList
                .Select(s => Path.Combine(s.ResultsDirectoryPath))
                .FirstOrDefault(Directory.Exists);

            if (artifactsResults is null)
            {
                Console.WriteLine("[XLBench] Could not locate BenchmarkDotNet results directory.");
                return;
            }

            var reports = Directory
                .GetFiles(artifactsResults, "*-report-github.md")
                .OrderBy(f => f)
                .ToList();

            if (reports.Count == 0)
            {
                Console.WriteLine($"[XLBench] No *-report-github.md files in {artifactsResults}.");
                return;
            }

            const string header =
                """
                <!-- Generated by XLBench. Do not edit by hand; re-run scripts/run-benchmarks.ps1. -->
                # XLBench Results

                Each section below embeds the full BenchmarkDotNet environment block (OS, CPU,
                .NET SDK and runtime). Timings are hardware-specific; treat the allocation/GC
                columns as the most portable signal across machines. Regenerate locally with
                `scripts/run-benchmarks.ps1`.


                """;

            var outFile = Path.Combine(docsDir, "results.md");
            using (var writer = new StreamWriter(outFile, append: false))
            {
                writer.Write(header);
                foreach (var report in reports)
                {
                    writer.WriteLine();
                    writer.Write(File.ReadAllText(report));
                    writer.WriteLine();
                }
            }

            Console.WriteLine($"[XLBench] Published {reports.Count} report(s) to {outFile}");
        }
    }
}
